### PR TITLE
Deck builder styling

### LINKED ISSUE #5: Style the deck builder
- [x] Organize sections
- [x] Style the statuses
- [x] Update buttons
- [x] Position the cards
- [x] Add appropriate elements tags for text and style accordingly

### PR DESCRIPTION
**Pull request by jbentley10**
Closes #5 

Another PR for you, @jimmynewsom! 

Please let me know what your thoughts are on the "Availability" text. It did my best to overlap it with the image, but it wasn't really working out so I decided to put it directly below the image. What do you think?

I think it would be kind of cool to have the name of the card and it's description in the app in addition to on the image, but I realize that would be a lot of data to manually input 😅

### CODE REVIEW

**Comment by jimmynewsom** [comment]
Hey John,

I am totally okay with putting the availability text below the image, but I think it's important we keep 3 cards per row for UX reasons. Otherwise it is a pain finding the cards you are looking for. Can you please fix that after the weekend when you are back? (no rush)

Also, if I'm understanding your second point correctly, all of the card data except the descriptions **is** in the app memory in the cardMap state object. It was probably unnecessary optimization, but for v1 of this I was trying not to make extra card objects if I didn't need to, so there is exactly one version of every card object inside that map, ie the singleton pattern, and you can get object references to them with the full card data via the card names (eg cardMap.get("Geralt of Rivia")).

But they have all the data fields in the CardData class all set up except the descriptions, (mostly because I forgot to add it to the unit_cards.csv file on the server, but it is more efficient this way so idk if I'll fix it... :) ) All of the data gets loaded by the getCardData function from the server or localStorage in the useEffect hook when you first load the Deckbuilder or the GwentClient components.

I **think** (but not sure) that in their game they have plain images without the icons and stuff and they put the "card views" together from that and card data, but they are using a more low level language, and re-rendering the cards is like the most expensive thing this app does CPU wise, so I've just been using the finished images with icons in this app because it's easier. But we could maybe change that in the future, it would probably make the SmallCardViews look better. I'm rewriting the GwentClient component right now so that it doesn't re-render everything every game update. Once that's done it might work.

**Comment by jimmynewsom** [comment]
Also, if it's possible to get it to look a little more like the reference images in the repo that would be incredible, but since you agreed to do this I feel like it's only fair you get to take the lead for styling decisions, so if you think this is better that's what we'll do.

**Comment by jimmynewsom** [comment]
One more comment for details. If you look at this [image](https://static.wikia.nocookie.net/witcher_gamepedia/images/1/1c/Tw3-gwent-game-01.png/revision/latest?cb=20150520221248) , you can see there are usually 2 views for cards. 1 with details for the deckbuilder screen and the big card in the actual game, and another small version for the players hand and the board. Now that I fixed the bug causing a bunch of unnecessary re-renders we could probably implement that if you wanted, I just need to find images for the cards without the banners and stuff. It's probably in the game files somewhere...

Also, usually the graveyards expand to show you the cards in them like [this](https://witcher-games.fandom.com/wiki/Gwent?file=Tw3-gwent-redraw-phase-01.png) but I haven't figured out how to do that yet. Any ideas as a react expert? I was thinking a transparent Dialog component might do the trick. Otherwise it just shows the top card in the graveyard next to the decks (bottom and top right).

**Comment by jbentley10** [comment]
Hey @jimmynewsom! 

Let me get back to you on the graveyard dialog once I start on styling the GwentClient. I'll have a better idea once I take a look at the gameplay itself! 

Until then, I've updated this PR with the styles you requested. Added a bunch of icons and laid out the DeckBuilder such that it matches the game a bit better. I also added icons for the filters. Let me know if you think there's anything else we should add for now!

**Review by jimmynewsom — APPROVED** [review]
:) Thank you. Looks great. Merging now

**Pull request merged**
